
version: '3.8'
services:

  prism:
    image: stoplight/prism:4
    command: mock -h 0.0.0.0 /openapi/swapi.yaml
    volumes:
      - ./openapi:/openapi
    ports:
      - "4010:4010"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4010/people" ]
      interval: 5s
      timeout: 3s
      retries: 20
    networks: [swapi_net]

  prism-proxy:
    image: stoplight/prism:4
    command: proxy -h 0.0.0.0 /openapi/swapi.yaml https://swapi.info/api
    volumes:
      - ./openapi:/openapi
    ports:
      - "4011:4010"
    networks:
      - swapi_net

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8080:8080"
    volumes:
      - ./openapi:/openapi
    environment:
      SWAGGER_JSON: /openapi/swapi.yaml
    networks:
      - swapi_net
    depends_on:
      - prism

  karate-job:
    image: karate-jre:latest
    profiles: ["tests-karate"]           # solo corre cuando activás el profile
    environment:
      BASE_URL: http://prism:4010
    working_dir: /src
    volumes:
      - ./karate:/src
    command: java -jar /karate.jar .
    networks:
      - swapi_net

  stepci-job:
    image: ghcr.io/stepci/stepci:latest
    profiles: ["tests-stepci"]           # solo corre cuando activás el profile
    volumes:
      - ./stepci:/stepci
      - ./openapi:/openapi
    environment:
      STEPCI_DISABLE_ANALYTICS: "1"
    networks: [swapi_net]
    healthcheck:
      disable: true
    command: ["/stepci/workflow.yml"]

  k6:
    image: grafana/k6:latest
    profiles: ["tests-k6"]            # solo corre cuando activás el profile
    environment:
      BASE_URL: "http://prism:4010/"  # o "https://swapi.info/api/"
    volumes:
      - ./k6:/k6
    command: ["run", "--summary-export=/k6/results/summary.json", "/k6/starwars.js"]
    networks: [swapi_net]

  zap-baseline:
    image: ghcr.io/zaproxy/zaproxy:stable
    profiles: ["security"]
    volumes:
      - ./zap:/zap/wrk
    command:
      [
        "zap-baseline.py",
        "-t","http://prism:4010",
        "-r","/zap/wrk/zap-baseline.html",
        "-d","-I"
      ]
    networks: [swapi_net]

  zap-automation:
    image: ghcr.io/zaproxy/zaproxy:weekly
    profiles: ["security"]
    volumes:
      - ./openapi/swapi.yaml:/zap/wrk/openapi.yaml:ro
      - ./zap/automation.yaml:/zap/wrk/automation.yaml:ro
      - ./zap:/zap/wrk
    # -cmd = modo CLI (no UI), -addonupdate = actualiza reglas, -autorun = ejecuta el YAML
    command:
      [
        "zap.sh","-cmd","-addonupdate",
        "-config","api.disablekey=true",
        "-autorun","/zap/wrk/automation.yaml"
      ]
    networks: [swapi_net]

networks:
  swapi_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.110.0/24
